### ISSUE TITLE
roadmap(modal): aggregation issue

### ISSUE THREAD

**Issue by EvilAlexei** [EvilAlexei/ngx-bootstrap#2]
### Demos
- [ ] docs(modal): demos should have following structure
   - Quick start
   - Properties
   - Styling
   - Custom content
   - Config
- [ ] docs(modal): add demo for scrolling long content
- [ ] docs(modal): add demo for modal with tooltips and popovers

### New functionality
- [ ] feat(modal): add aria support
- [ ] feat(modal): implement key navigation support
- [ ] feat(modal): implement data attributes service
  - Options
  - Dynamic init/insert
- [ ] feat(modal): component custom template
- [ ] feat(modal): `handleUpdate` method for readjust the modal’s position

## Component acceptance criteria:
- [ ] Adding to project / Quick start
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
   - ngmodel
   - ngmodel + custom validation
   - reactive forms
   - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
